# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Front_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1010, 633)
        Dialog.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        Dialog.setMouseTracking(False)
        Dialog.setFocusPolicy(QtCore.Qt.StrongFocus)
        Dialog.setStyleSheet("background-color:rgb(58, 58, 58);")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(180, 10, 641, 81))
        font = QtGui.QFont()
        font.setFamily("Poor Richard")
        font.setPointSize(48)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("color:rgb(255, 255, 255);\n"
"font: 48pt \"Poor Richard\";")
        self.label.setTextFormat(QtCore.Qt.RichText)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(860, 600, 141, 16))
        self.label_3.setStyleSheet("color:rgb(255, 24, 3);\n"
"")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 131, 61))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("Images/PreBo_cmyk.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(860, 10, 131, 101))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("Images/37153.jpg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.splitter = QtWidgets.QSplitter(Dialog)
        self.splitter.setGeometry(QtCore.QRect(60, 290, 911, 101))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.BTN_fir = QtWidgets.QPushButton(self.splitter)
        font = QtGui.QFont()
        font.setFamily("Small Fonts")
        font.setBold(True)
        font.setWeight(75)
        self.BTN_fir.setFont(font)
        self.BTN_fir.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.BTN_fir.setStyleSheet("background-color:rgb(85, 255, 0);\n"
"border-radius:25px;")
        self.BTN_fir.setObjectName("BTN_fir")
        self.BTN_slm = QtWidgets.QPushButton(self.splitter)
        font = QtGui.QFont()
        font.setFamily("Small Fonts")
        font.setBold(True)
        font.setWeight(75)
        self.BTN_slm.setFont(font)
        self.BTN_slm.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.BTN_slm.setAutoFillBackground(False)
        self.BTN_slm.setStyleSheet("background-color:rgb(85, 255, 0);\n"
"border-radius:25px;")
        self.BTN_slm.setObjectName("BTN_slm")
        self.BTN_py = QtWidgets.QPushButton(self.splitter)
        font = QtGui.QFont()
        font.setFamily("Small Fonts")
        font.setBold(True)
        font.setWeight(75)
        self.BTN_py.setFont(font)
        self.BTN_py.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.BTN_py.setStyleSheet("background-color:rgb(85, 255, 0);\n"
"border-radius:25px;")
        self.BTN_py.setObjectName("BTN_py")
        self.BTN_lsa = QtWidgets.QPushButton(self.splitter)
        font = QtGui.QFont()
        font.setFamily("Small Fonts")
        font.setBold(True)
        font.setWeight(75)
        self.BTN_lsa.setFont(font)
        self.BTN_lsa.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.BTN_lsa.setStyleSheet("background-color:rgb(85, 255, 0);\n"
"border-radius:25px;\n"
"color:rgb(0, 0, 0)")
        self.BTN_lsa.setObjectName("BTN_lsa")
        self.BTN_epc = QtWidgets.QPushButton(self.splitter)
        font = QtGui.QFont()
        font.setFamily("Small Fonts")
        font.setBold(True)
        font.setWeight(75)
        self.BTN_epc.setFont(font)
        self.BTN_epc.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.BTN_epc.setMouseTracking(True)
        self.BTN_epc.setTabletTracking(False)
        self.BTN_epc.setAcceptDrops(True)
        self.BTN_epc.setStyleSheet("background-color:rgb(85, 255, 0);\n"
"border-radius:25px;")
        self.BTN_epc.setObjectName("BTN_epc")
        self.label.raise_()
        self.BTN_slm.raise_()
        self.BTN_py.raise_()
        self.BTN_epc.raise_()
        self.BTN_fir.raise_()
        self.label_3.raise_()
        self.BTN_lsa.raise_()
        self.label_4.raise_()
        self.label_2.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:20pt;\">Valve Plate, Spring, Filler Piece &amp; Clamping sleeve assembly</span></p></body></html>"))
        self.label_3.setText(_translate("Dialog", "Developed By PREBO"))
        self.BTN_fir.setText(_translate("Dialog", "Line Rejection"))
        self.BTN_slm.setText(_translate("Dialog", "Secondary Level\n"
"  Maintainance"))
        self.BTN_py.setText(_translate("Dialog", "POKA-YOKE"))
        self.BTN_lsa.setText(_translate("Dialog", "Line_Setup"))
        self.BTN_epc.setText(_translate("Dialog", "Tool_Monitoring"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
